spring:
  application:
    name: bn-auth-service
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    url: jdbc:postgresql://localhost:5432/bnauth
    username: bn
    password: secret123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  jwt:
    secret: myVerySecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
    expiration: 86400000

  server:
    port: 8080
